INSERT INTO public.admin_project (slug, title, type, summary, tags, status, sort_order, source_url, demo_url, preview_image)
VALUES
  ('coming-soon', 'Coming Soon', 'PERSONAL', 'Placeholder for a personal project showcase.', 'Personal,In Progress', 'PLANNED', 99, NULL, NULL, NULL),
  ('local-service-landing', 'Local Service Landing Page', 'PERSONAL', 'Service business template with trust badges, services, and CTA flow.', 'Template,Landing Page,Services', 'ARCHIVED', 1, '/portfolio/preview/local-service', 'https://github.com/rianidewi/portfolio-projects/tree/main/landing-pages/local-service.html', '/portfolio/images/previews/local-service.jpg'),
  ('event-landing', 'Event Landing Page', 'PERSONAL', 'Conference/event template with schedule, speakers, and ticket CTA.', 'Template,Landing Page,Event', 'ARCHIVED', 2, '/portfolio/preview/event', 'https://github.com/rianidewi/portfolio-projects/tree/main/landing-pages/event.html', '/portfolio/images/previews/event.jpg'),
  ('app-launch-landing', 'App Launch Landing Page', 'PERSONAL', 'App launch template with highlights, ratings, and store CTAs.', 'Template,Landing Page,App', 'ARCHIVED', 3, '/portfolio/preview/app-launch', 'https://github.com/rianidewi/portfolio-projects/tree/main/landing-pages/app-launch.html', '/portfolio/images/previews/app-launch.jpg'),
  ('product-landing', 'Product Landing Page', 'PERSONAL', 'Single-product template with benefits, pricing, and purchase CTA.', 'Template,Landing Page,Product', 'ARCHIVED', 4, '/portfolio/preview/product', 'https://github.com/rianidewi/portfolio-projects/tree/main/landing-pages/product.html', '/portfolio/images/previews/product.jpg'),
  ('company-landing', 'Company Landing Page', 'PERSONAL', 'B2B company template with solutions, stats, and contact CTA.', 'Template,Landing Page,Company', 'ARCHIVED', 5, '/portfolio/preview/company', 'https://github.com/rianidewi/portfolio-projects/tree/main/landing-pages/company.html', '/portfolio/images/previews/company.jpg'),
  ('procure-to-pay-workflow', 'Procure-to-Pay Workflow', 'EXPERIENCE', 'End-to-end P2P flow covering requisition, PO, GR, invoice, and payment.', 'Workflow,ERP,Finance', 'ACTIVE', 6, '/portfolio/source/procure-to-pay-workflow/java', 'https://github.com/rianidewi/portfolio-projects/tree/main/Procure_To_Pay_Workflow', NULL),
  ('order-to-cash-workflow', 'Order-to-Cash Workflow', 'EXPERIENCE', 'Sales order execution with delivery, invoicing, and collections lifecycle.', 'Workflow,ERP,Sales', 'ACTIVE', 7, '/portfolio/source/order-to-cash-workflow/java', 'https://github.com/rianidewi/portfolio-projects/tree/main/Order_To_Cash_Workflow', NULL),
  ('record-to-report-workflow', 'Record-to-Report Workflow', 'EXPERIENCE', 'Close and reporting workflow from journals to period close and reporting.', 'Workflow,ERP,Accounting', 'ACTIVE', 8, '/portfolio/source/record-to-report-workflow/java', 'https://github.com/rianidewi/portfolio-projects/tree/main/Record_To_Report_Workflow', NULL),
  ('hire-to-retire-workflow', 'Hire-to-Retire Workflow', 'EXPERIENCE', 'HR lifecycle flow from hiring to onboarding, payroll, and offboarding.', 'Workflow,ERP,HR', 'ACTIVE', 9, '/portfolio/source/hire-to-retire-workflow/java', 'https://github.com/rianidewi/portfolio-projects/tree/main/Hire_To_Retire_Workflow', NULL),
  ('inventory-replenishment-workflow', 'Inventory Replenishment Workflow', 'EXPERIENCE', 'Demand-driven replenishment with reorder, GR, and stock updates.', 'Workflow,ERP,Inventory', 'ACTIVE', 10, '/portfolio/source/inventory-replenishment-workflow/java', 'https://github.com/rianidewi/portfolio-projects/tree/main/Inventory_Replenishment_Workflow', NULL),
  ('returns-rma-workflow', 'Returns / RMA Workflow', 'EXPERIENCE', 'Return approvals with GR return, inspection, and credit note handling.', 'Workflow,ERP,Operations', 'ACTIVE', 11, '/portfolio/source/returns-rma-workflow/java', 'https://github.com/rianidewi/portfolio-projects/tree/main/Returns_Rma_Workflow', NULL)
ON CONFLICT (slug) DO UPDATE
SET preview_image = COALESCE(EXCLUDED.preview_image, public.admin_project.preview_image);
